name: onecx-product-store
home: ""
sources: []
version: 0.0.0
description: ""
keywords: []
maintainers: []
icon: ""
apiversion: v2
condition: ""
tags: ""
appversion: 0.0.0
deprecated: false
annotations: {}
kubeversion: ""
dependencies:
- name: onecx-product-store-svc
  version: 0.0.0-rc.6
  repository: oci://ghcr.io/onecx/charts
  condition: ""
  tags: []
  enabled: false
  importvalues: []
  alias: ""
type: ""
